arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_1
    - Joint_2
    - Joint_9
    - Joint_10
    - Joint_17
    - Joint_18
  gains:
    Joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_17:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_18:
      p: 100
      d: 1
      i: 1
      i_clamp: 1